name: CI with Slack Notification

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Slack Notification
        uses: act10ns/slack@v2.1.0
        with:
          status: 200
          message: hello
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
